version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - sd2k
    assignees:
      - sd2k
  - package-ecosystem: cargo
    directory: "/grafana-plugin-sdk-macros"
    schedule:
      interval: daily
    reviewers:
      - sd2k
    assignees:
      - sd2k
