version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - sd2k
    assignees:
      - sd2k
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
