[package]
name = "grafana-plugin-sdk-rust"
version = "0.1.0"
authors = ["Ben Sully <ben@bsull.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { git = "https://github.com/sd2k/tonic", branch = "codegen-dont-export-stream" }
prost = "0.7.0"

[build-dependencies]
tonic-build = { git = "https://github.com/sd2k/tonic", branch = "codegen-dont-export-stream" }
